name: SonarCloud
on:
  push:
    branches:
      - main
      - - /.*HU.*/
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Analyze with SonarCloud
        run: ./mvnw -B verify sonar:sonar -Dsonar.projectKey=jav-eas-472-cognitive-service-mngr -Dsonar.organization=javeriana-especializacion-aes-ing-soft -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$EAS_SONAR_TOKEN
        env:
          AES_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EAS_SONAR_TOKEN: ${{ secrets.EAS_SONAR_TOKEN }}
